Repository github-F4F/F4F-FE, pull requests merged in 2024-06, with the labels that each got.

#3 [chore] 프리티어 & 린트 설정
  .prettierrc
Labels: chore

#5 [Chore] 글로벌 스타일 & theme 설정
  src/main.tsx
  src/styles/GlobalStyle.ts
  src/styles/index.tsx
  src/styles/theme.ts
Labels: chore

#10 [chore]: tsconfig & vite.config.ts 내 emotion css 속성 사용가능하도록 속성 추가
  tsconfig.json
  vite.config.ts
Labels: chore

#11 [chore]: prettier width 변경
  .prettierrc
Labels: chore

#13 [Chore] reset 재설정 (padding & margin)
  src/styles/GlobalStyle.ts
  src/styles/theme.ts
Labels: chore, feat

#15 [Feat] 라우터 설정
  src/App.tsx
  src/pages/home/HomePage.tsx
  src/pages/search/SearchPage.tsx
  src/router/Router.ts
  src/router/Router.tsx
  src/router/route.ts
Labels: feat

#17 [Feat] 공통 버튼 컴포넌트 구현
  src/components/@common/button/Button.style.ts
  src/components/@common/button/Button.tsx
  src/styles/theme.ts
Labels: common

#19 [Chore] yarn svgr 세팅
  package.json
  public/svg/ic_arrow.svg
  src/assets/custom.d.ts
  src/assets/svg/IcArrow.tsx
  src/assets/svg/index.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: chore

#20 [Feat] 헤더 레이아웃 추가, Gmarket 폰트 추가
  index.html
  public/assets/images/git.png
  src/App.tsx
  src/layout/Header.tsx
  src/layout/Layout.tsx
  src/styles/theme.ts
Labels: common

#22 [Feat] 팔로우 검색 페이지 UserInfo 컴포넌트 추가
  package.json
  src/apis/client.ts
  src/apis/getUser.ts
  src/components/@common/loading/Loading.tsx
  src/components/@common/loading/loading.json
  src/hooks/queries/key/index.ts
  src/hooks/queries/useGetUser.ts
  src/main.tsx
  src/pages/search/SearchPage.tsx
  src/pages/search/component/UserInfo.tsx
  yarn.lock
Labels: API, common, feat

#23 [Feat] homepage UI 구현
  src/assets/svg/IcArrow.tsx
  src/components/@common/button/Button.tsx
  src/components/@common/input/Input.style.ts
  src/components/@common/input/Input.tsx
  src/components/bar/Bar.style.ts
  src/components/bar/Bar.tsx
  src/pages/home/HomePage.style.ts
  src/pages/home/HomePage.tsx
Labels: styles

#31 [Feat] Vercel 배포
  .github/workflows/vercelDeploy.yml
  vercel.json
Labels: feat

#28 [Feat] 팔로잉 사용자 리스트
  package.json
  src/apis/followUser.ts
  src/apis/getFollowUser.ts
  src/apis/unFollowUser.ts
  src/hooks/queries/key/index.ts
  src/hooks/queries/useFollowUser.ts
  src/hooks/queries/useGetFollowList.ts
  src/hooks/queries/useGetUser.ts
  src/hooks/queries/useUnFollowUser.ts
  src/pages/search/SearchPage.tsx
  src/pages/search/component/Card.tsx
  src/pages/search/component/CardList.tsx
  src/pages/search/component/UserInfo.tsx
  yarn.lock
Labels: feat

#29 [Feat] 팔로워리스트 구현
  index.html
  src/apis/getUser.ts
  src/hooks/queries/key/index.ts
  src/hooks/queries/useFollowerInfiniteQuery.ts
  src/pages/search/SearchPage.tsx
  src/pages/search/component/CardList.tsx
  src/pages/search/component/followerLIstBox/FollowerListBox.style.ts
  src/pages/search/component/followerLIstBox/FollowerListBox.tsx
  src/pages/search/component/followerLists/FollowerLists.tsx
Labels: API, feat
